"""initial

Revision ID: 0001
Revises:
Create Date: 2026-06-08 22:05:31.783537

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "telemetry_event",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("event", sa.String(length=32), nullable=False),
        sa.Column("client_id", sa.String(length=36), nullable=True),
        sa.Column("code_hash", sa.String(length=64), nullable=True),
        sa.Column("webgpu_supported", sa.Boolean(), nullable=True),
        sa.Column("device_class", sa.String(length=128), nullable=True),
        sa.Column("browser", sa.String(length=128), nullable=True),
        sa.Column("metrics", sa.JSON(), nullable=True),
        sa.Column("error_kind", sa.String(length=32), nullable=True),
        sa.Column("ts", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_telemetry_event")),
    )
    with op.batch_alter_table("telemetry_event", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_telemetry_event_client_id"), ["client_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_telemetry_event_created_at"), ["created_at"], unique=False
        )

    op.create_table(
        "user",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("github_id", sa.Integer(), nullable=True),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("display_name", sa.String(length=255), nullable=True),
        sa.Column("is_guest", sa.Boolean(), nullable=False),
        sa.Column("ui_language", sa.String(length=8), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user")),
        sa.UniqueConstraint("github_id", name=op.f("uq_user_github_id")),
    )
    op.create_table(
        "review_session",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("title", sa.String(length=120), nullable=False),
        sa.Column("language", sa.String(length=32), nullable=True),
        sa.Column("review_mode", sa.String(length=16), nullable=False),
        sa.Column("model_version", sa.String(length=64), nullable=False),
        sa.Column("prompt_version", sa.String(length=64), nullable=False),
        sa.Column("code_text", sa.Text(), nullable=False),
        sa.Column("code_hash", sa.String(length=64), nullable=False),
        sa.Column("review_output", sa.Text(), nullable=False),
        sa.Column("timing", sa.JSON(), nullable=True),
        sa.Column("client_id", sa.String(length=36), nullable=True),
        sa.Column("device_class", sa.String(length=128), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
            name=op.f("fk_review_session_user_id_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_review_session")),
    )
    with op.batch_alter_table("review_session", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_review_session_client_id"), ["client_id"], unique=False
        )
    # Composite hot-path index (user_id, created_at DESC). Autogenerate skips it because
    # SQLite can't reflect expression-based indexes, so it is added by hand (backend.md §5.2).
    op.create_index(
        "ix_review_user_created",
        "review_session",
        ["user_id", sa.text("created_at DESC")],
        unique=False,
    )

    op.create_table(
        "feedback",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("rating", sa.String(length=4), nullable=False),
        sa.Column("reason_tags", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["review_session.id"],
            name=op.f("fk_feedback_session_id_review_session"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_feedback")),
    )
    with op.batch_alter_table("feedback", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_feedback_session_id"), ["session_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("feedback", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_feedback_session_id"))

    op.drop_table("feedback")
    op.drop_index("ix_review_user_created", table_name="review_session")
    with op.batch_alter_table("review_session", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_review_session_client_id"))

    op.drop_table("review_session")
    op.drop_table("user")
    with op.batch_alter_table("telemetry_event", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_telemetry_event_created_at"))
        batch_op.drop_index(batch_op.f("ix_telemetry_event_client_id"))

    op.drop_table("telemetry_event")
    # ### end Alembic commands ###
